### ISSUE TITLE
No processing Story Arc

### ISSUE THREAD

**Issue by mikecul** [evilhero/mylar#1253]
Hi,

I have set up a few story arcs (which are now finished so it is just a case of downloading back issues) - they download fine, when they can be found, however no post processing takes place at all. Below is an extract from my log which seems to relate to story arcs

2016-04-17 12:47:05 ERROR   Uncaught exception: Traceback (most recent call last):
File "/Applications/Mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/Applications/Mylar/mylar/webserve.py", line 535, in addStoryArc
self.ArcWatchlist(storyarcid)
File "/Applications/Mylar/mylar/webserve.py", line 2562, in ArcWatchlist
valids = [x for x in filelist if re.sub('[|\s]','', x['dynamic_name'].lower()).strip() == re.sub('[|\s]','', mod_arc.lower()).strip()]
TypeError: 'NoneType' object is not iterable
2016-04-17 12:47:05 INFO    {'comiccount': 0}
2016-04-17 12:47:05 INFO    there are 0 files.
2016-04-17 12:47:05 INFO    [DIRECTORY-CHECK] Creating comic directory (0777) : /Users/michaelcullen/Downloads/Comics/StoryArcs/Civil War
2016-04-17 12:47:05 WARNING [DIRECTORY-CHECK] Could not find comic directory: /Users/michaelcullen/Downloads/Comics/StoryArcs/Civil War
2016-04-17 12:47:05 INFO    Story Arc Directory [/Users/michaelcullen/Downloads/Comics/StoryArcs/Civil War] does not exist! - attempting to create now.
2016-04-17 12:46:51 INFO    [STORY ARC][40615] Successfully found Story Arc ComicVine ID [4045-40615] within db. Preparing to refresh Story Arc.
2016-04-17 12:45:48 INFO    Validating Directory (/Users/michaelcullen/Downloads/Comics/StoryArcs). Already exists! Continuing...
2016-04-17 12:45:30 INFO    Validating Directory (/Users/michaelcullen/Downloads/Comics/StoryArcs). Already exists! Continuing...

any help would be appreciated :) i am using it on Mac if that makes any difference.

Thanks

Mike

**Comment by mikecul** [comment]
Hi - just to add to this, i got this error when adding a new story arc, could it be related?

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 535, in addStoryArc
    self.ArcWatchlist(storyarcid)
  File "/Applications/Mylar/mylar/webserve.py", line 2562, in ArcWatchlist
    valids = [x for x in filelist if re.sub('[\|\s]','', x['dynamic_name'].lower()).strip() == re.sub('[\|\s]','', mod_arc.lower()).strip()]
TypeError: 'NoneType' object is not iterable

**Comment by evilhero** [comment]
Yep, was a bug in the adding of the arcs. When it was added, it didn't create a special field that's used when post-processing for proper matching - it's fixed in the development commit that just went up a few moments ago (and also the subsequent error you posted is fixed as well - both were related).

Best bet is to delete the arc from your arc watchlist, and then re-add it again just to make sure everything flows smoothly.

**Comment by mikecul** [comment]
great thanks, do i need to manually update mylar, or will it do it automatically? by the way, loving the program!

**Comment by evilhero** [comment]
You'll have to manually update it - you can force it to do a check to see if its up to date by either stopping / starting mylar, or going into the Manage tab / Advanced options / Check for updates.  Both will display a pop up indicating an update is available, and you can click within the popup to update.

**Comment by mikecul** [comment]
great thanks, just updated and still get the below when i add an arc

Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 541, in addStoryArc
    self.ArcWatchlist(storyarcid)
  File "/Applications/Mylar/mylar/webserve.py", line 2568, in ArcWatchlist
    valids = [x for x in filelist if re.sub('[\|\s]','', x['dynamic_name'].lower()).strip() == re.sub('[\|\s]','', mod_arc.lower()).strip()]
NameError: global name 'mod_arc' is not defined

but it did do the post processing correctly 👍 so maybe its a red herring?

**Comment by evilhero** [comment]
Yeah there was an additional reference to it just below the original error,  which I never hit on my quick test as I didn't have any story arc files already present in the directory. 

 Fix is up in development now ;)
