### ISSUE TITLE
Error During Manual Search

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1358]
Similar to last issue I had, but this one references nzbname instead.

> Uncaught exception: Traceback (most recent call last):
> File "/home/ben/mylar/mylar/logger.py", line 158, in new_run
> old_run(_args, *_kwargs)
> File "/usr/lib/python2.7/threading.py", line 754, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/home/ben/mylar/mylar/webserve.py", line 1368, in queueissue
> foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
> File "/home/ben/mylar/mylar/search.py", line 232, in search_init
> findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
> File "/home/ben/mylar/mylar/search.py", line 1517, in NZB_SEARCH
> nzbname = nzbname_create(nzbprov, info=comicinfo, title=ComicTitle) #entry['title'])
> File "/home/ben/mylar/mylar/search.py", line 1880, in nzbname_create
> logger.fdebug("nzbname used for post-processing:" + nzbname)
> UnboundLocalError: local variable 'nzbname' referenced before assignment

**Comment by evilhero** [comment]
Can you throw up the debug lines leading up to this error so I can see how the traceback occurred and using which method?

**Comment by BenBeyond** [comment]
> 2016-08-24 15:45:59	ERROR	Uncaught exception: Traceback (most recent call last):
File "/home/ben/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/ben/mylar/mylar/webserve.py", line 1368, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/home/ben/mylar/mylar/search.py", line 232, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/home/ben/mylar/mylar/search.py", line 1517, in NZB_SEARCH
nzbname = nzbname_create(nzbprov, info=comicinfo, title=ComicTitle) #entry['title'])
File "/home/ben/mylar/mylar/search.py", line 1880, in nzbname_create
logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignmen
2016-08-24 15:45:59	DEBUG	integer value of issue we have found : 11000
2016-08-24 15:45:59	DEBUG	issue we found for is : 011
2016-08-24 15:45:59	DEBUG	integer value of issue we are looking for : 11000
2016-08-24 15:45:59	DEBUG	issue we are looking for is : 11
2016-08-24 15:45:59	DEBUG	this should be a match!
2016-08-24 15:45:59	DEBUG	it's a go captain... - we matched 100.0%!
2016-08-24 15:45:59	DEBUG	Match to series : 100.0 %.
2016-08-24 15:45:59	DEBUG	splitit-len:1
2016-08-24 15:45:59	DEBUG	scount:1
2016-08-24 15:45:59	DEBUG	word matched on : archie
2016-08-24 15:45:59	DEBUG	0 Comparing: archie .to. archie
2016-08-24 15:45:59	DEBUG	scount : 0
2016-08-24 15:45:59	DEBUG	splitit: archie
2016-08-24 15:45:59	DEBUG	Watchlist-length: 1
2016-08-24 15:45:59	DEBUG	search-length: 1
2016-08-24 15:45:59	DEBUG	length match..proceeding
2016-08-24 15:45:59	DEBUG	len-watchcomic : 1
2016-08-24 15:45:59	DEBUG	splitst : 1
2016-08-24 15:45:59	DEBUG	['archie'] watchlist word count: 1
2016-08-24 15:45:59	DEBUG	['archie', '011'] nzb series word count: 1
2016-08-24 15:45:59	DEBUG	adjusting from: archie 011 to: 011
2016-08-24 15:45:59	DEBUG	adjusted nzb comic and issue: archie 011
2016-08-24 15:45:59	DEBUG	original nzb comic and issue: archie 011
2016-08-24 15:45:59	INFO	allow_packs:False
2016-08-24 15:45:59	INFO	rss:yes
2016-08-24 15:45:59	INFO	WWT
2016-08-24 15:45:59	DEBUG	Scanner detected: son of ultron-empire
2016-08-24 15:45:59	DEBUG	mini-series detected : son of ultron-empire
2016-08-24 15:45:59	DEBUG	5. Bracket Word: son of ultron-empire
2016-08-24 15:45:59	DEBUG	digital edition detected
2016-08-24 15:45:59	DEBUG	3. Bracket Word: digital
2016-08-24 15:45:59	DEBUG	2016 - right years match baby!
2016-08-24 15:45:59	DEBUG	year looking for: 2016
2016-08-24 15:45:59	DEBUG	year detected: 2016
2016-08-24 15:45:59	DEBUG	1. Bracket Word: 2016
2016-08-24 15:45:59	DEBUG	ComVersChk : 2
2016-08-24 15:45:59	DEBUG	UseFuzzy is : None
2016-08-24 15:45:59	DEBUG	Comic: archie 011
2016-08-24 15:45:59	DEBUG	0. Bracket Word: archie 011
2016-08-24 15:45:59	DEBUG	Cleantitle: archie 011 (2016) (digital) (son of ultron-empire)
2016-08-24 15:45:59	DEBUG	Cleantitle: archie 011 (2016) (digital) (son of ultron-empire)
2016-08-24 15:45:59	DEBUG	Removed extension from filename: .cbr
2016-08-24 15:45:59	DEBUG	Entry: Archie 011 (2016) (digital) (Son of Ultron-Empire).cbr
2016-08-24 15:45:59	DEBUG	Wed, 24 Aug 2016 14:54:04 +0100 is after store date of 2016-08-24
2016-08-24 15:45:59	DEBUG	size given as: 54.0 MB
2016-08-24 15:45:59	DEBUG	sub:Archie 011 (2016) (digital) (Son of Ultron-Empire).cbr
2016-08-24 15:45:59	DEBUG	checking search result: Archie 011 (2016) (digital) (Son of Ultron-Empire).cbr
2016-08-24 15:45:59	DEBUG	titleend: 011 (2016) (digital) (son of ultron empire)
2016-08-24 15:45:59	DEBUG	matched on series title: Archie
2016-08-24 15:45:59	DEBUG	matched to : Archie 011 (2016) (digital) (Son of Ultron-Empire).cbr
2016-08-24 15:45:59	DEBUG	6 - formatrem_seriesname :archie
2016-08-24 15:45:59	DEBUG	53 - formatrem_torsplit : archie 011 (2016) (digital) (son of ultron empire)cbr
2016-08-24 15:45:59	DEBUG	tor-Title: Archie 011 (2016) (digital) (Son of Ultron-Empire).cbr
2016-08-24 15:45:59	DEBUG	seriesname_alt:None
2016-08-24 15:45:58	DEBUG	tsearch : archie%
2016-08-24 15:45:58	DEBUG	ComicID: 83121
2016-08-24 15:45:58	DEBUG	Sending request to [TPSE] RSS for Archie : 011
2016-08-24 15:45:58	DEBUG	calpha/cnumber: None / None
2016-08-24 15:45:58	INFO	Shhh be very quiet...I'm looking for Archie issue: 11 (2016) using TPSE [RSS]
2016-08-24 15:45:58	INFO	allow_packs set to :False
2016-08-24 15:45:58	DEBUG	Initiating Search via : rss
2016-08-24 15:45:58	INFO	search provider order is ['tpse']
2016-08-24 15:45:58	DEBUG	provider order sequence is now to start with tpse at spot #0
2016-08-24 15:45:58	DEBUG	torrent provider found: tpse
2016-08-24 15:45:58	DEBUG	checking against torrent provider: tpse
2016-08-24 15:45:58	DEBUG	found provider in existing enabled providers.
2016-08-24 15:45:58	DEBUG	Usenet Retention : 1500 days
2016-08-24 15:45:58	DEBUG	there are : 0 nzb providers you have selected.
2016-08-24 15:45:58	DEBUG	there are : 1 torrent providers you have selected.
2016-08-24 15:45:58	DEBUG	nzbprovider(s): []
2016-08-24 15:45:58	DEBUG	Checking for torrent enabled.
2016-08-24 15:45:58	INFO	Issue Title given as : None
2016-08-24 15:45:58	DEBUG	Publisher is : Archie Comics
2016-08-24 15:45:58	INFO	Initiating manual search for Archie issue: 11
2016-08-24 15:45:58	DEBUG	mode:want
2016-08-24 15:45:58	DEBUG	ComicID:83121

**Comment by evilhero** [comment]
Should be fixed in the next development commit - sorry for the delay in response...

**Comment by BenBeyond** [comment]
Sounds Good.  Is there anything I can do in the short term to get issue downloads working again? I have since realized that even the automatic RSS feed searches are failing to download anything as well.

**Comment by evilhero** [comment]
There's a few other problems that relate to TPSE, mainly that they started using cloudflare protection which seems to kick on like clockwork from Wed-Fri, so mylar can't retrieve any results currently when it's on. 

I have a fix going up in the next development that will fix the name issue of your original post, as well as being able to retrieve results from TPSE even if they have the protection on. 

Hope to get it out later tonight or early tomorrow (pending life stuff of course).

**Comment by BenBeyond** [comment]
Still get the same or similar Error:

> 2016-09-08 16:51:09
ERROR
Uncaught exception: Traceback (most recent call last):
File "/home/ben/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/ben/mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/home/ben/mylar/mylar/search.py", line 233, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/home/ben/mylar/mylar/search.py", line 1522, in NZB_SEARCH
nzbname = nzbname_create(nzbprov, info=comicinfo, title=ComicTitle) #entry['title'])
File "/home/ben/mylar/mylar/search.py", line 1885, in nzbname_create
logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment

**Comment by evilhero** [comment]
Is it being snatched from wwt, dem, or tpse? I had tested against wwt and it worked fine at the time..

**Comment by BenBeyond** [comment]
Here is the complete debug log from log clear to manual search on an issue:

> 2016-09-08 17:06:18	ERROR	Uncaught exception: Traceback (most recent call last):
File "/home/ben/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/ben/mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/home/ben/mylar/mylar/search.py", line 233, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/home/ben/mylar/mylar/search.py", line 1522, in NZB_SEARCH
nzbname = nzbname_create(nzbprov, info=comicinfo, title=ComicTitle) #entry['title'])
File "/home/ben/mylar/mylar/search.py", line 1885, in nzbname_create
logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment
2016-09-08 17:06:18	DEBUG	integer value of issue we have found : 9000
2016-09-08 17:06:18	DEBUG	issue we found for is : 009
2016-09-08 17:06:18	DEBUG	integer value of issue we are looking for : 9000
2016-09-08 17:06:18	DEBUG	issue we are looking for is : 9
2016-09-08 17:06:18	DEBUG	this should be a match!
2016-09-08 17:06:18	DEBUG	it's a go captain... - we matched 100.0%!
2016-09-08 17:06:18	DEBUG	Match to series : 100.0 %.
2016-09-08 17:06:18	DEBUG	splitit-len:2
2016-09-08 17:06:18	DEBUG	scount:2
2016-09-08 17:06:18	DEBUG	word matched on : girls
2016-09-08 17:06:18	DEBUG	1 Comparing: girls .to. girls
2016-09-08 17:06:18	DEBUG	scount : 1
2016-09-08 17:06:18	DEBUG	splitit: girls
2016-09-08 17:06:18	DEBUG	word matched on : paper
2016-09-08 17:06:18	DEBUG	0 Comparing: paper .to. paper
2016-09-08 17:06:18	DEBUG	scount : 0
2016-09-08 17:06:18	DEBUG	splitit: paper
2016-09-08 17:06:18	DEBUG	Watchlist-length: 2
2016-09-08 17:06:18	DEBUG	search-length: 2
2016-09-08 17:06:18	DEBUG	length match..proceeding
2016-09-08 17:06:18	DEBUG	len-watchcomic : 2
2016-09-08 17:06:18	DEBUG	splitst : 2
2016-09-08 17:06:18	DEBUG	['paper', 'girls'] watchlist word count: 2
2016-09-08 17:06:18	DEBUG	['paper', 'girls', '009'] nzb series word count: 2
2016-09-08 17:06:18	DEBUG	adjusting from: paper girls 009 to: 009
2016-09-08 17:06:18	DEBUG	adjusted nzb comic and issue: paper girls 009
2016-09-08 17:06:18	DEBUG	original nzb comic and issue: paper girls 009
2016-09-08 17:06:18	INFO	allow_packs:False
2016-09-08 17:06:18	INFO	rss:yes
2016-09-08 17:06:18	INFO	WWT
2016-09-08 17:06:18	DEBUG	5. Bracket Word: minutemen-faessla
2016-09-08 17:06:18	DEBUG	digital edition detected
2016-09-08 17:06:18	DEBUG	3. Bracket Word: digital
2016-09-08 17:06:18	DEBUG	2016 - right years match baby!
2016-09-08 17:06:18	DEBUG	year looking for: 2016
2016-09-08 17:06:18	DEBUG	year detected: 2016
2016-09-08 17:06:18	DEBUG	1. Bracket Word: 2016
2016-09-08 17:06:18	DEBUG	Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
2016-09-08 17:06:18	DEBUG	ComVersChk : 0
2016-09-08 17:06:18	DEBUG	UseFuzzy is : None
2016-09-08 17:06:18	DEBUG	Comic: paper girls 009
2016-09-08 17:06:18	DEBUG	0. Bracket Word: paper girls 009
2016-09-08 17:06:18	DEBUG	Cleantitle: paper girls 009 (2016) (digital) (minutemen-faessla)
2016-09-08 17:06:18	DEBUG	Cleantitle: paper girls 009 (2016) (digital) (minutemen-faessla)
2016-09-08 17:06:18	DEBUG	Removed extension from filename: .cbz
2016-09-08 17:06:18	DEBUG	Entry: Paper Girls 009 (2016) (digital) (Minutemen-Faessla).cbz
2016-09-08 17:06:18	DEBUG	Wed, 07 Sep 2016 17:37:19 +0100 is after store date of 2016-09-07
2016-09-08 17:06:18	DEBUG	size given as: 40.7 MB
2016-09-08 17:06:18	DEBUG	sub:Paper Girls 009 (2016) (digital) (Minutemen-Faessla).cbz
2016-09-08 17:06:18	DEBUG	checking search result: Paper Girls 009 (2016) (digital) (Minutemen-Faessla).cbz
2016-09-08 17:06:18	DEBUG	titleend: 009 (2016) (digital) (minutemen faessla)
2016-09-08 17:06:18	DEBUG	matched on series title: Paper Girls
2016-09-08 17:06:18	DEBUG	matched to : Paper Girls 009 (2016) (digital) (Minutemen-Faessla).cbz
2016-09-08 17:06:18	DEBUG	11 - formatrem_seriesname :paper girls
2016-09-08 17:06:18	DEBUG	55 - formatrem_torsplit : paper girls 009 (2016) (digital) (minutemen faessla)cbz
2016-09-08 17:06:18	DEBUG	tor-Title: Paper Girls 009 (2016) (digital) (Minutemen-Faessla).cbz
2016-09-08 17:06:18	DEBUG	seriesname_alt:None
2016-09-08 17:06:18	DEBUG	tsearch : paper%girls%
2016-09-08 17:06:18	DEBUG	ComicID: 85128
2016-09-08 17:06:18	DEBUG	Sending request to [TPSE] RSS for Paper Girls : 009
2016-09-08 17:06:18	DEBUG	calpha/cnumber: None / None
2016-09-08 17:06:18	INFO	Shhh be very quiet...I'm looking for Paper Girls issue: 9 (2016) using TPSE [RSS]
2016-09-08 17:06:18	INFO	allow_packs set to :False
2016-09-08 17:06:18	DEBUG	Initiating Search via : rss
2016-09-08 17:06:18	INFO	search provider order is ['tpse']
2016-09-08 17:06:18	DEBUG	provider order sequence is now to start with tpse at spot #0
2016-09-08 17:06:18	DEBUG	torrent provider found: tpse
2016-09-08 17:06:18	DEBUG	checking against torrent provider: tpse
2016-09-08 17:06:18	DEBUG	found provider in existing enabled providers.
2016-09-08 17:06:18	DEBUG	Usenet Retention : 1500 days
2016-09-08 17:06:18	DEBUG	there are : 0 nzb providers you have selected.
2016-09-08 17:06:18	DEBUG	there are : 1 torrent providers you have selected.
2016-09-08 17:06:18	DEBUG	nzbprovider(s): []
2016-09-08 17:06:18	DEBUG	Checking for torrent enabled.
2016-09-08 17:06:18	INFO	Issue Title given as : None
2016-09-08 17:06:18	DEBUG	Publisher is : Image
2016-09-08 17:06:18	INFO	Initiating manual search for Paper Girls issue: 9
2016-09-08 17:06:18	DEBUG	mode:want
2016-09-08 17:06:18	DEBUG	ComicID:85128
2016-09-08 17:06:03	INFO	Web logs cleared
