### ISSUE TITLE
Mylar broke after update

### ISSUE THREAD

**Issue by Tailchakra** [evilhero/mylar#1929]
The entire app doesn't start anymore after the update.
Using the Linuxserver/Mylar docker

```File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
File "/app/mylar/Mylar.py", line 26, in <module>
import mylar
File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
File "/app/mylar/Mylar.py", line 26, in <module>
import mylar
File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
File "/app/mylar/Mylar.py", line 26, in <module>
import mylar
File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
File "/app/mylar/Mylar.py", line 26, in <module>
import mylar
File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'```

**Comment by evilhero** [comment]
Can you start mylar in debug mode from the cli and see if any additional info is present?

Also, what is your python locale set to? If you don't know how to check - from within a python cli enter ```import locale; locale.getdefaultlocale()``` and it will spit out your locale as well as your default encoding.

**Comment by galacticat** [comment]
I am getting the same issue.

I am taking a guess, but it looks like the locale isn't set?

```
root@mylar:/$ python
Python 2.7.14 (default, Dec 14 2017, 15:51:29)
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale; locale.getdefaultlocale()
(None, None)
>>>
```

**Docker Logs:**

```
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/app/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/app/mylar/mylar/logger.py", line 41, in <module>
    if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by evilhero** [comment]
Yeah, there was a fix a gent did to fix the locale problem but it was a manual docker fix so I couldn't put it in (https://github.com/claym/docker-mylar/commit/083b3461edbd0c27a6151ee529e5519353bac222)

I'm curious, what does it to do when you do a simple ```locale``` from your shell cli?

**Comment by galacticat** [comment]
```
Python 2.7.14 (default, Dec 14 2017, 15:51:29)
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> locale
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'locale' is not defined
>>>
```

**Comment by evilhero** [comment]
Heh, not from a python cli - from your shell cli. The python locale is supposed to be basically a wrapper for the shell locale command.

**Comment by galacticat** [comment]
Yep, adding the ENV variables to my `docker run` command fixes it.

` -e LANG=en_US.UTF-8 -e LANGUAGE en_US:en -e LC_ALL=en_US.UTF-8`

**Comment by evilhero** [comment]
Weird, but I guess I can understand how docker is limiting the env on purpose. Thanks for helping to troubleshoot and even confirming the solution. Other people that are using docker will have this problem, so this can be a good reference for them ;)

**Comment by Tailchakra** [comment]
So much activity since I posted ha! that fixed it indeed

**Comment by ronlipke** [comment]
Was getting this same error running without docker on macOS 11.13.  Adding the same Environment Variables to the Lauch Agent plist solved it.

```<key>EnvironmentVariables</key>
	<dict>
		<key>LANG</key>
		<string>en_US.UTF-8</string>
		<key>LANGUAGE</key>
		<string>en_US:en</string>
		<key>LC_ALL</key>
		<string>en_US.UTF-8</string>
	</dict>
```

**Comment by cclick815** [comment]
How can I add this fix to my Synology Package? I not currently using Docker with it, just been doing a git pull to do the updates to the outdated community package.

**Comment by evilhero** [comment]
No clue - Synopkg installs are synopkg community so you'd have to ask there. I have nothing to do with the pkg stuff.

Make sure it's the exact error that's posted in this issue, as it might be something totally unrelated.

**Comment by WedgeSparda** [comment]
I'm not being able to run Mylar anymore on my Synology. I'm not getting any log (or I can't find it) and can't figure out what's happening. I uninstalled the package but after reinstall he's more than 500 updates behind the current master version, and when I update it doesn't start anymore. 

I now that Mylar doesn't have nothing to do with Synology but we're completely lost here and I can't find any help.

**Comment by evilhero** [comment]
Looks like your pkg_resources module isn't there any more for some reason. You have to reinstall it, but I'm not sure if things are different for synopkg installs. Normally it's either ```pip install pkg_resources --upgrade``` or ```sudo apt-get install python-pkg-resources``` (for Ubuntu /debian)

**Comment by WedgeSparda** [comment]
@evilhero Thanks, that point me on the right direction and now is working 😀

**Comment by Eikelman** [comment]
Any quickfix for unRAID dockers?

**Comment by evilhero** [comment]
If you're getting an error like above, you'd probably have to change the docker settings like those did above.

Otherwise, I haven't a clue about anything related to the unRAID docker.

**Comment by dabadgreek** [comment]
I am having the same issue with on synology but running as a package not through docker. I see the same logger error in logger.py but when I run the pip command listed above I get an error saying cannot find a version that satisfies the requirement pkg_resources.

**Comment by dhirenmehta** [comment]
@WedgeSparda Can I ask how you fixed this in the end? I'm having the same issue but not sure what to do on my Synology system

**Comment by WedgeSparda** [comment]
@dhirenmehta I had to install pip with this command `curl https://bootstrap.pypa.io/get-pip.py | python` I had to run it as super user so first I executed `sudo -su`.

Hope it helps.

**Comment by dabadgreek** [comment]
@WedgeSparda I have pip installed on synology but when i run pip command: pip install pkg_resources --upgrade I get the "cannot find a version that satisfies the requirement  pkg_resources" what directory are you running the pip command in?

**Comment by WedgeSparda** [comment]
@dabadgreek Did you tried to run the same command as admin with sudo?

**Comment by dabadgreek** [comment]
@WedgeSparda I tried it as su and with sudo get same error each time.. 
Collecting pkg_resources
  Could not find a version that satisfies the requirement pkg_resources (from versions: )
No matching distribution found for pkg_resources

**Comment by evilhero** [comment]
@dabadgreek : are you running master / development? I just pushed a fix that will set a default locale if nothing can be determined.

**Comment by dabadgreek** [comment]
@evilhero I am running master

**Comment by evilhero** [comment]
Fix is in both branches now.

**Comment by phaelon74** [comment]
The fix is not in for Windows.  I just downloaded Mylar via Git and it is still broken:

C:\>python c:\Mylar\Mylar.py
  File "c:\Mylar\Mylar.py", line 66
    print 'language detected as non-English (%s). Forcing specific logging module - errors WILL NOT be captured in the logs' % logger.LOG_LANG
                                                                                                                           ^
SyntaxError: invalid syntax

Locale and Region, Date/Time are all set correctly.  Problem persists.  Can we get the fix added to the Windows Branch of code too please?

**Comment by evilhero** [comment]
The fix is in for Windows - and it's in the most recent branches of each.

Are you postive that you are are runing Mylar with python 2.7.x - not python 3.x? As that error message is very typical for being run with python3 (ie. there's nothing wrong with the syntax in python 2.7.x)

**Comment by evilhero** [comment]
It shouldn't matter - the ComicRN script gets the full path directly from the download client. So as long as Mylar can reach the path (ie. permissions), it should have no problem post-processing stuff.  It's gone thru an update the last month or so, so make sure that you have an API Key set within Mylar and you use that in the autoProcessComics.cfg file instead of using a username/password. Also with the new comicRN script, you need to make sure you have requests installed for full compatibility (it can be installed on *nix systems with just a ```pip install requests```), because it operates outside of the Mylar directory and is executed outside of it, you have to make sure that requests is installed on your OS.

You can also try to use the Completed Download Handling (CDH) as well - all it is is just a checkbox for the given nzb downloader in the mylar GUI and that's it. Just make sure if you do use CDH, that you don't use the comicRN script as well - that causes race conditions and you'll get weird errors on post-processing saying stuff hasn't post-processed/partially post-processed when it very well could have.

Fire back any problems you have and we'll get it going for ya ;)

**Comment by phaelon74** [comment]
Man, all of what you just said, I had done, ROFL.  I was quadruple processing.  Thanks again!
